### ISSUE TITLE
Replace deprecated kubernetes APIs

### ISSUE THREAD

**Issue by thrucker** [actano/pact_broker#2]
https://github.com/actano/pact_broker/blob/2c45383dbff11c8eee6547ac7810818b04c4af44/charts/pactbroker/templates/deployment.yaml uses a deprecated kubernetes API which soon will be removed. See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

**Comment by qisaw** [comment]
Closed by https://github.com/actano/pact_broker/commit/f46a265a261d4780a8b4d00977effbc264848e24
